### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by viko16** [viko16/vue-ghpages-blog#1]
目前还是挺简陋的，至少缺了这些功能
- [x] 搜索
- [ ] ~~SEO~~
- [x] HTML5 History Mode
- [ ] 过渡动画
- [ ] TOC
- [ ] GraphQL API v4
- [ ] PWA

### Q & A
- Q: 为什么没用用上 GitHub API v4 ?
  A: GraphQL API 暂时还[不支持匿名调用](https://platform.github.community/t/permit-access-without-oauth-token/2572) 😢 
-

**Comment by epver** [comment]
目前见过最简洁的vue版gh-pages了, 直接拿去用了,嘿嘿

**Comment by viko16** [comment]
@cheneyliu 没问题～

过奖了，近期也打算用 Vue 2.x 重写一遍，也顺便把这个 issue 的坑也填上吧哈哈

**Comment by IniZio** [comment]
不太明白你說的分頁是指..?

**Comment by viko16** [comment]
@IniZio Can you speak Chinese ? 分页是指在 List View 拆分成多页显示，不至于看起来太长了。

**Comment by IniZio** [comment]
剛在自己的blog 實現了search by title, 不知可不可以滿足你的搜索功能? 我可以PR.

**Comment by viko16** [comment]
@IniZio PR welcome. 😄

**Comment by IniZio** [comment]
搜索 PR #11

**Comment by IniZio** [comment]
不過我覺得infinite scroll 可能比分頁更好?

**Comment by LetHergo** [comment]
喜欢这样的~

**Comment by luckypoem** [comment]
没看见分页功能 能实现分页功能吗？

**Comment by viko16** [comment]
@luckypoem 暂时没有，以后会加上的。

其实从 GitHub API  请求回来就是整个列表，所以分页实际上也是前端截断而已。

**Comment by playmyswift** [comment]
请问你是如何处理请求限制的 
```json
{
  "message": "API rate limit exceeded for 116.216.128.233. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```

**Comment by viko16** [comment]
@jiakeqi 唔，所以我基于 sessionStorage 加了个简单缓存
https://github.com/viko16/vue-ghpages-blog/blob/develop/src/api/index.js#L31

**Comment by zhuziyi1989** [comment]
Nodejs 版本低了还不行。
