### ISSUE TITLE
SEO 问题

### ISSUE THREAD

**Issue by zypeh** [viko16/vue-ghpages-blog#16]
首先我非常喜欢这样的架构，也用这个来练 Vue 力。

想知道关于 #1 todolist 里的 SEO 问题，是用 SSR (Server-Side Rendering) 吗？或者是有更好的方法？

**Comment by viko16** [comment]
@zypeh 感谢支持。

说来惭愧，#1 上的问题到了 2017 了我都还没解决完...

SEO 问题可能暂时不会在代码层面解决了，因为这个库的重点在于无需生成直接放在 GitHub Pages。
而 SSR 需要服务器支持，从这个角度来说原则上有点出入。

**Comment by zypeh** [comment]
原来如此。
嗯嗯，我只是想知道有没有办法在 Github Pages 上解决 SEO 问题而已。谢谢 :)

**Comment by viko16** [comment]
@zypeh 哈哈，如果发现有更好的解决方法，欢迎回来跟我说一声。

**Comment by playmyswift** [comment]
以目前来看, 应该是没有的, 只能用 nodejs 服务端渲染. 享受不到 github pages 的便利了

**Comment by viko16** [comment]
@zypeh @jiakeqi 

或许可以看看这个
https://www.npmjs.com/package/prerender-spa-plugin

**Comment by playmyswift** [comment]
👍 好
