### ISSUE TITLE
为何网站不显示内容？

### ISSUE THREAD

**Issue by luckypoem** [viko16/vue-ghpages-blog#17]
hi.
我按你的repo在自己的vps上搭建了博客 http://vgb.bright.biz.st/ ，不过为何网站不显示内容？
root@AR:/usr/local/vue-ghpages-blog# cat src/conf.json
{
  "blogTitle": "Unknow Me",
  "repo": "luckypoem/writings",
  "path": "posts",
  "branch": master,
  "favicon": null
}
root@AR:/usr/local/vue-ghpages-blog#

我修改了conf.json,难道是conf.json没改对？

**Comment by viko16** [comment]
@luckypoem 你的 `conf.json` 没有写错，是 [posts/test-1.md](https://github.com/luckypoem/writings/blob/master/posts/test-1.md) 这篇文章的标题不对，导致在列表中提取不出日期来，可以参考其他文章的文件名格式

**Comment by luckypoem** [comment]
现在搞好了：http://vgb.bright.biz.st ，不过有个匪夷所思的问题，就是http://vgb.bright.biz.st 页面里的帖子我只能直接点击，才打得开。如果我在选择在新开的页面中打开，会显示： not found. 复制某个帖子的链接地址，在新开的浏览器tab里，访问也是打不开的，也显示：not found. 比如这个帖子：
http://vgb.bright.biz.st/post/5b76ed01804907271cfb73afb26c9abc7598d94f ，我估计你直接访问它，也是打不开的。
怎么解决？

**Comment by viko16** [comment]
这是因为开启了 vue-router 的 history 模式。

## 解决方法

A. 如果你能配置服务器
修改一下你的服务器配置（看了一下你的网站响应头是 Apache）
```
<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteBase /
  RewriteRule ^index\.html$ - [L]
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteRule . /index.html [L]
</IfModule>
```

B. 如果不能
那就简单地将 `router/index.js` 里面把 `mode: 'history'` 改成 `mode: 'hash'`

## 详细说明
http://router.vuejs.org/zh-cn/essentials/history-mode.html
