### ISSUE TITLE
请问不绑定CNAME可以访问吗

### ISSUE THREAD

**Issue by ghost** [viko16/vue-ghpages-blog#19]
你好，我没有绑定CNAME，使用travis-ci构建是ok的，

直接使用 https://webbings.github.io/vue-ghpages-blog/  访问时空白的，哪里有问题呢？

**Comment by viko16** [comment]
你好，是可以的。不过有两处地方需要修改一下：

1. [webpack.config.js#L23](https://github.com/viko16/vue-ghpages-blog/blob/develop/webpack.config.js#L23)   由绝对路径改成相对路径

   ```diff
   - publicPath: '/',
   + publicPath: './',
   ```

2. [src/router/index.js#L23](https://github.com/viko16/vue-ghpages-blog/blob/develop/src/router/index.js#L23)   使用 URL hash 值来作路由

   ```diff
   export default new VueRouter({
   - mode: 'history',
   + mode: 'hash',
     routes
   })
   ```

   参考链接： https://router.vuejs.org/zh-cn/essentials/history-mode.html

   ​

**Comment by viko16** [comment]
对了，`src/tpl.html` 里的 `/manifest.json` 也需要改成相对路径

**Comment by ghost** [comment]
非常感谢！已经可以访问。PS：project 很 cool
