### ISSUE TITLE
关于服务器端渲染markdown

### ISSUE THREAD

**Issue by zytx121** [viko16/vue-ghpages-blog#20]
您好！我看到你在[将 Markdown 渲染交给 GitHub](http://ukn.me/post/d2056d8e3399e912c0c3907e56995d152d10aa97)一文中写道，您将之前的获取了 Markdown 的 raw 形式，然后使用 JavaScript 在浏览器端进行渲染和代码高亮着色的改成了使用`xhr.setRequestHeader("Accept", "application/vnd.github.v3.html")`接口。

可是我fork下来的你的最新版本中貌似还是使用的是老的浏览器端渲染。
比如：
src/utils/render.js 
 api/index.js文件中的 ` headers: { Accept: 'application/vnd.github.v3.raw' }`

**Comment by viko16** [comment]
嗯，是的，从升级到 vue 2.x 之后的版本的确是换成浏览器渲染了。

原因是现在的版本，文章开头里利用 front-matter 带上一些标题日期信息，而这个操作在 GitHub 的 markdown 服务端渲染的时候是做不到的，所以现在已经改回前端读取 front-matter 和 markdown 渲染了。

忘记更新博文，很抱歉给你带来困扰了.. 😢

**Comment by viko16** [comment]
另外，如果需要 GitHub 渲染的话，可以看看 [vue-1 的版本](https://github.com/viko16/vue-ghpages-blog/tree/vue-1).

**Comment by zytx121** [comment]
原来如此！
感谢作者回复的这么及时！
另外，我在测试 `Accept: application/vnd.github.v3.html`时，为什么返回的还是base64编码的数据？
![image](https://user-images.githubusercontent.com/10410257/28416100-2c8d3134-6d85-11e7-9144-e6fc8ca63f6a.png)
而`Accept: application/vnd.github.v3.raw`是对的。
![image](https://user-images.githubusercontent.com/10410257/28416193-833856bc-6d85-11e7-89c4-a5e78332a177.png)
是不是我的理解有问题，返回的渲染好的markdown是还需要解码吗？

***

另外我也读了您代码中的关于的front-matter部分，也就是用hash值获取文章详情的时候只会得到一个文本，无法知道哪些部分是标题，哪些部分是日期是的意思吧。貌似是这样，嗯- -！
不成熟的小建议：能否将在list页面点击某一文章标题时，将文章的名称和日期当作参数传给文章详情页，从而省去用front-matter解析文章内容这一步，然后改回github服务器markdown渲染呢？

因为本人刚接触vue，所以不知道这样的改动是否复杂，有没有价值？如果有的话，非常愿意PR！刚才看了下，子组件之间传递参数貌似需要vuex？

再次感谢作者的回复！

**Comment by viko16** [comment]
## Postman 问题
`Accept: application/vnd.github.v3.raw` 返回的是文本，`Accept: application/vnd.github.v3.html` 返回的才是 base64 encode，看你截图里只是 key 前面的 √ 没选对

## front-matter 问题
获取到文本后，通过 [front-matter@2](https://www.npmjs.com/package/front-matter) 可以解析出 title & date

## 传参问题
我是这样考虑的，从 list 切换到 post 可以带上需要的参数，可是如果直接访问 post 页呢？
比如你直接打开 http://ukn.me/post/d2056d8e3399e912c0c3907e56995d152d10aa97 的时候，title & date 只能从页面本身获取了

## Vuex 问题
额，我觉得暂时数据流动还是比较简单的，暂时没考虑引入 Vuex   (毕竟一共才两个页面啊噗..

**Comment by zytx121** [comment]
确实，这样的数据流很简洁也很巧妙。不需要vuex就完成了hash参数的传递。赞！是我考虑不周了。
