### ISSUE TITLE
...

### ISSUE THREAD

**Issue by leekoho** [viko16/vue-ghpages-blog#23]
你的博客《一些前端工具站点》中，CSS三角形生成工具链接改了，[https://leekoho.github.io/](https://leekoho.github.io/)

**Comment by leekoho** [comment]
找不到你的联系方式了，忘谅解

**Comment by viko16** [comment]
已经更新了，谢谢你 😄

**Comment by leekoho** [comment]
你是怎么找到我的网站的啊？   我很好奇

**Comment by viko16** [comment]
@leekoho 哈哈，Google 搜索 「CSS三角形生成」，前排的就是你的站了
