### ISSUE TITLE
搜索框输入关键词后跳转错误的页面

### ISSUE THREAD

**Issue by WayneGongCN** [viko16/vue-ghpages-blog#24]
搜索框输入关键词后跳转错误的页面

**Comment by WayneGongCN** [comment]
搜索功能有没有考虑过用 [https://developer.github.com/v3/search/#search-code](https://developer.github.com/v3/search/#search-code) 这个接口实现？

可以做到标题和全文搜索。

**Comment by viko16** [comment]
@zowiegong 有道理耶！

但是有点担心，每次都调用接口查询，很快就会消耗完 GitHub API 每小时 60 次的次数限制。有什么思路吗？
https://developer.github.com/v3/#rate-limiting

**Comment by WayneGongCN** [comment]
搜索的接口限制特殊些： 非验证用户 每分钟 10 个请求，并且与其他接口分开计算的。
[https://developer.github.com/v3/search/#rate-limit](https://developer.github.com/v3/search/#rate-limit)

搜索的额度用完了很快（一分钟）就会恢复，而且不会影响到 Repositories 这边的使用。

**Comment by viko16** [comment]
赞啊！有兴趣来个 PR 吗？
