### ISSUE TITLE
history mode for using anchors and TOC

### ISSUE THREAD

**Issue by IniZio** [viko16/vue-ghpages-blog#9]
I modified the project a bit to use markdown-it and its plugins. one of it is anchor. However since this projects router uses hash mode it misunderstands the link and puts the anchor right at the root of url. If I change the path of `build.js` to `/build.js` and change the mode to `history`, it works. 

Therefore want to ask it is more preferable to make the change? I can make a PR for that.

**Comment by IniZio** [comment]
#10

**Comment by viko16** [comment]
Thank you IniZio,

I've tried the HTML5 History Mode but failed in just few months ago.

To use this mode, you have to do some serve configurations (URL Rewrite) but unfortunately GitHub Pages doesn't support any server side configuration. That is why I am still using `hash` mode.  Deeply regret and I am looking for other methods to solve this problem.
- Some discussion:  https://github.com/isaacs/github/issues/408
- Vue-router documentation:  http://router.vuejs.org/en/essentials/history-mode.html

**Comment by IniZio** [comment]
I tried to use the method on my [blog](inizio.github.io), and it seems to be working to my expectation. Would you mind reviewing my code at the develop branch of the repo to see if the method is simply not feasible?

**Comment by viko16** [comment]
Access from List is work. (Because our browser support `HTML5 pushState API` )

But if you refresh, it will request from GitHub Pages server and get the 404 response 🙈.

eg. http://inizio.github.io/post/b4ed1f5e7939732e07e7ad35b9af18588a509297

**Comment by viko16** [comment]
In addition, what's the meaning of TOC 🤔 ?

**Comment by IniZio** [comment]
Hmm ok understood, will close the PR then. TOC means Table Of Contents, just want to make it pair with anchors.

**Comment by viko16** [comment]
I will add it into TODO #1  and keep exploring the solution.

Thank you for your contribution. @IniZio
